"""Steam-less launcher: run the game through PortProton.

PortProton runs an arbitrary Windows executable when passed its path, reusing
the Flatpak's bundled Wine/Proton and prefix. A ``.desktop`` entry is written
alongside the launch script.
"""

from __future__ import annotations

from pathlib import Path

from .base import Launcher, LaunchResult, _quote


class PortProtonLauncher(Launcher):
    kind = "portproton"

    def register(self, name: str, exe: Path, game_dir: Path) -> LaunchResult:
        body = (
            "#!/usr/bin/env bash\n"
            "# Generated by steam-dl -- run through PortProton without Steam.\n"
            f"exec {self.cfg.flatpak_bin} run {self.cfg.portproton_app} "
            f"{_quote(exe)} \"$@\"\n"
        )
        script = self._write_script(name, body)
        desktop = self._write_desktop(name, script, game_dir)
        return LaunchResult(
            kind=self.kind,
            files=[script, desktop],
            note=f"Run: {script}\nLaunches via PortProton; also in the app menu.",
        )
