"""Steam-less launcher: run the game under Proton via umu-launcher.

umu-run (the Unified Launcher for Windows games) runs a Windows executable
under Proton with no Steam client. ``PROTONPATH=GE-Proton`` makes umu fetch and
use the latest GE-Proton automatically. A ``.desktop`` entry is also written so
the game shows up in the application menu.
"""

from __future__ import annotations

from pathlib import Path

from .base import Launcher, LaunchResult, _quote


class ScriptLauncher(Launcher):
    kind = "script"

    def register(self, name: str, exe: Path, game_dir: Path) -> LaunchResult:
        body = (
            "#!/usr/bin/env bash\n"
            "# Generated by steam-dl -- run under Proton without Steam.\n"
            'export GAMEID="${GAMEID:-0}"\n'
            f'export PROTONPATH="${{PROTONPATH:-{self.cfg.proton_tool}}}"\n'
            f"exec umu-run {_quote(exe)} \"$@\"\n"
        )
        script = self._write_script(name, body)
        desktop = self._write_desktop(name, script, game_dir)
        return LaunchResult(
            kind=self.kind,
            files=[script, desktop],
            note=(
                f"Run: {script}\n"
                "Requires umu-launcher (umu-run). Also added to the app menu."
            ),
        )
